# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Edit here with the names of your latex file and directory (can use ".")
      DIR: .
      FILE_FULL_TEXT: cv
      FILE_ONE_PAGE: cv-one-page
    steps:
      - name: Set up Git repository for EN version
        uses: actions/checkout@v3
        with:
          ref: en
          path: en
      - name: Set up Git repository for ZH-CN version
        uses: actions/checkout@v3
        with:
          ref: zh-cn
          path: zh-cn
      - name: cv-en
        uses: dante-ev/latex-action@latest
        with:
          root_file: |
            ${{ env.FILE_FULL_TEXT }}
            ${{ env.FILE_ONE_PAGE }}
          working_directory: ${{ env.DIR }}/en
      - name: cv-zh-cn
        uses: dante-ev/latex-action@latest
        with:
          root_file: |
            ${{ env.FILE_FULL_TEXT }}
            ${{ env.FILE_ONE_PAGE }}
          working_directory: ${{ env.DIR }}/zh-cn
      - name: move
        run: mkdir -p github_artifacts/en && mv ${{ env.DIR }}/en/*.pdf ./github_artifacts/ && mkdir -p github_artifacts/zh-cn && mv ${{ env.DIR }}/zh-cn/*.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: personal-cv-files
          path: ./github_artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
